### ISSUE TITLE
Indices of square brackets break expressions

### ISSUE THREAD

**Issue by lucidyan** [orsharir/github-mathjax#12]
For example
$$\mathbb{E}[\Delta \theta^2 ]_t$$ $$\mathbb{E}[\Delta \theta^2]_{t - 1}$$

**Comment by orsharir** [comment]
It's a limitation of adding math in as a post-processing step on Github -- it's due to the processing of underline as part of Markdown for italicized text. If you escape the underlines with a slash, i.e. ``\_``, then it does work. As example if you use the following code instead:
```latex
$$\mathop{\mathbb{E}}[\Delta \theta^2 ]\_t$$
$$E[\Delta \theta^2]\_{t - 1}$$
```
then you get:

$$\mathop{\mathbb{E}}[\Delta \theta^2 ]\_t$$
$$E[\Delta \theta^2]\_{t - 1}$$

**Comment by lucidyan** [comment]
Oh, thanks, i've got it! When i was writing that issue, I mention that if equations was delimited by new line, then escaping underscore is not even needed.

$$\mathbb{E}[\Delta \theta^2 ]_t$$ 

$$\mathbb{E}[\Delta \theta^2]_{t - 1}$$
